import com.google.protobuf.gradle.*
import org.gradle.plugins.ide.idea.model.IdeaModel

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.0.1/userguide/tutorial_java_projects.html
 */

buildscript {
    dependencies {
        classpath("com.google.protobuf:protobuf-gradle-plugin:0.8.10")
    }
}

plugins {
    // Apply the java plugin to add support for Java
    java

    // Apply the application plugin to add support for building a CLI application.
    application

    idea
}

apply(plugin = "com.google.protobuf")

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:28.0-jre")

    // Use JUnit test framework
    testImplementation("junit:junit:4.12")
}

application {
    // Define the main class for the application.
    mainClassName = "traefik.repro.App"
}

val Project.protobuf: ProtobufConvention
    get() =
        this.convention.getPlugin(ProtobufConvention::class)

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.10.0"
    }

    plugins {
        id("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:1.25.0"
        }
    }

    generateProtoTasks {
        ofSourceSet("main").forEach { task ->
            task.plugins {
                id("grpc")
            }
        }
    }
}

configure<IdeaModel> {
    module {
        generatedSourceDirs.add(file("build/generated/source/proto/main/java"))
        generatedSourceDirs.add(file("build/generated/source/proto/main/grpc"))
    }
}

dependencies {
    implementation("com.google.protobuf:protobuf-java:3.10.0")
    implementation("com.google.api.grpc:proto-google-common-protos:1.17.0")
    implementation("com.google.protobuf:protobuf-java:3.10.0")
    implementation("io.grpc:grpc-core:1.25.0")
    implementation("io.grpc:grpc-protobuf:1.25.0")
    implementation("io.grpc:grpc-stub:1.25.0")
    implementation("io.grpc:grpc-services:1.25.0")
    implementation("io.grpc:grpc-netty:1.25.0")
    implementation("io.netty:netty-tcnative-boringssl-static:2.0.26.Final")
    implementation("javax.annotation:javax.annotation-api:1.3.2")

}